# Generated by Django 4.1.7 on 2023-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_content_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
