# Generated by Django 4.1.7 on 2023-11-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_portfolio_alter_content_details_alter_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.RemoveField(
            model_name='values',
            name='image',
        ),
    ]
