# Generated by Django 4.1.7 on 2023-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kartlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=400)),
                ('img', models.ImageField(upload_to='files/covers')),
            ],
        ),
        migrations.CreateModel(
            name='Tasarimlarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=400)),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.TextField(max_length=200)),
            ],
        ),
    ]
