# Generated by Django 4.1.7 on 2023-11-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tasarimlarim_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasarimlarim',
            new_name='Design',
        ),
    ]
