# Generated by Django 4.1.7 on 2023-11-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_design_img_alter_kartlar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='ictenImg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
